In [1]:
import math


In [11]:
#Esercizio 1)
mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]] #lista con più liste 

print (mat[0][3]) #stampato l'elemento nell'indice 0 alla colonna 3
print (mat[1][3]) #stampato l'elemento nell'indice 1 alla colonna 3
print (mat[2][3]) #stampato l'elemento nell'indice 2 alla colonna 3

3
8
13


In [18]:
#Esercizio 2)
numero = 3

math.sin(numero)

0.1411200080598672

In [19]:
math.factorial(numero)

6

In [20]:
math.cos(numero)

-0.9899924966004454

In [24]:
#Esercizio 3)
math.degrees(math.pi)


180.0

In [25]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [33]:
#Esericizio 4)
import numpy as np

lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst = np.array(lst) #lista convertita in array

type(lst)

max_vendita= np.max(lst) #massimo nelle vendite
min_vendita= np.min(lst) #minimo nelle vendite
maggiori_5000= lst[lst>5000] #vendite maggiori di 5000
minori_3000= lst[lst<3000] #vendite minori di 3000
media_mensile= np.mean(lst) #media di vendite mensile

print (max_vendita)
print (min_vendita)
print (maggiori_5000)
print (minori_3000)
print (media_mensile)

8150
1280
[5500 7200 6410 8150 7100 5350]
[2000 1280 1900 2500]
4634.166666666667


In [37]:
#Esercizio 5)
import pandas as pd
fatturati_dict = {1997: 12_000, 1998: 15_000, #il dizionario crea una raccolta di coppie valori-chiave immutabili con qualsiasi tipo di dato
                  1999: 20_000, 2000: 23_000, 
                  2001: 25_000, 2002: 17_000, 
                  2003: 14_000, 2004: 21_000}

#la series permette di fare più operazioni di modifica perchè permette la manipolazione della struttura dei dati, al contrario del dizionario, 
#ma solo dati dello stesso tipo al contrario del dizionario che può averne diversi
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005)) 

fatturati_dict[1997] 
fatturati_series[1997]

np.int64(12000)

In [81]:
#Esercizio 6) Metodo FOR
import numpy as np

stipendi = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])

for stipendio in stipendi:
    stipendio *=2
    print (stipendio)

200
400
600
800
1000
1200
1400
1600
1800
2000


In [84]:
#Esercizio 6) Metodo MASKING
import numpy as np

stipendi = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])

stipendi * 2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [36]:
#Esercizio 7) 

In [ ]:
#Esercizio 8)

In [14]:
#Esercizio 9) 

input_str = input("Inserisci una lista di numeri separati da spazio: ") #inserire lista numeri da utente
numeri = list(map(int, input_str.split())) #creare una lista nominata numeri in cui ogni elemento è un intero dell'input seperato da uno spazio

for num in numeri: #ciclo for per ogni numero in numeri
    print('*' * num)

Inserisci una lista di numeri separati da spazio:  5 6 3 4


*****
******
***
****


In [18]:
#Esercizio 10)
lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]

cf_con_95 = [] #lista vuota che prenderà i codici che hanno 95 in essi

for cf in lista_cf:   #ciclo for per ogni elemento per vedere se è presente 95
    if "95" in cf:
        cf_con_95.append(cf) #aggiungere elementi in lista vuota creata prima se si verifica la condizione
        nome_cognome = cf[0:6] #range di elementi del CF per prendere il nome e cognome
        print(f"Codice fiscale: {cf}")
        print(f"Nome e Cognome: {nome_cognome}")
        print()  # riga vuota per leggibilità

print("Codici fiscali che contengono '95':")
print(cf_con_95)

Codice fiscale: ABCDEF95G01A123B
Nome e Cognome: ABCDEF

Codice fiscale: STUVWX95Z04A654E
Nome e Cognome: STUVWX

Codice fiscale: DEFGHI95J06A987G
Nome e Cognome: DEFGHI

Codici fiscali che contengono '95':
['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']


In [24]:
#Esercizio 11)

studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"] 
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"] 
edizioni = [1, 2, 3, 2, 2, 1, 3, 3]

for i in range(len(studenti)): #per ogni elemento nel range di studenti
    if edizioni[i] == 1: #se corrisponde a la posizione dell'elemento 1
        print(studenti [i]) #stampa l'elemento corrispondente 
   


Alex
Faith


In [25]:
#Esercizio 12)

prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"]
prezzi_doll = [prezzo.replace ("€","$") for prezzo in prezzi] #per ogni prezzo in prezzi, rimpiazza l'euro col dollaro
print (prezzi_doll)

['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [22]:
#Esercizio 13)

studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"]

squadra_pari = [] #Lista pari
squadra_dispari = [] #lista dispari

for i, nome in enumerate(studenti): #per ogni elemento di studenti 
    if i % 2 == 0: #se diviso 2 non dà resto (modulo) allora è pari
      
        squadra_pari.append(nome) #aggiungi il nome a pari
    else:
        squadra_dispari.append(nome) #altrimenti aggiungi a dispari

print("Squadra con posizioni pari:", squadra_pari)
print("Squadra con posizioni dispari:", squadra_dispari)

Squadra con posizioni pari: ['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
Squadra con posizioni dispari: ['Bob', 'Dan', 'Faith', 'Henry', 'John']


In [35]:
#Esercizio 14)

guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50]

somma_precedenti = 0 #variabile a 0 per poter aver una somma sui cui lavorare

#predisposizione dei mesi
for i in range(len(guadagni)): #per ogni elemento di guadagni
    guadagno_corrente = guadagni[i] #nuova variabile per semplificare
    mese = i + 1 #incremento di 1
    
   
    if i == 0: #se il primo è elemento è nella posizione zero ovvero il primo, la media precedente è zero
        media_precedenti = 0
        print(f"Mese {mese}: {guadagno_corrente} € (nessuna media precedente)") #calcolo del primo mese con stampa di testo esclusivo
    else:
        media_precedenti = somma_precedenti / i #formula media
        
        #confronto tra i guadagni 
        if guadagno_corrente > media_precedenti:
            confronto = "maggiore"
        elif guadagno_corrente < media_precedenti:
            confronto = "minore"
        else:
            confronto = "uguale" 
        print(f"Mese {mese}: {guadagno_corrente} € (media prec: {media_precedenti:.2f} € - il guadagno attuale è {confronto})")
    
    somma_precedenti += guadagno_corrente #aggiorna la somma tra i mesi precedenti e il mese corrente

Mese 1: 100 € (nessuna media precedente)
Mese 2: 90 € (media prec: 100.00 € - il guadagno attuale è minore)
Mese 3: 70 € (media prec: 95.00 € - il guadagno attuale è minore)
Mese 4: 40 € (media prec: 86.67 € - il guadagno attuale è minore)
Mese 5: 50 € (media prec: 75.00 € - il guadagno attuale è minore)
Mese 6: 80 € (media prec: 70.00 € - il guadagno attuale è maggiore)
Mese 7: 90 € (media prec: 71.67 € - il guadagno attuale è maggiore)
Mese 8: 120 € (media prec: 74.29 € - il guadagno attuale è maggiore)
Mese 9: 80 € (media prec: 80.00 € - il guadagno attuale è uguale)
Mese 10: 20 € (media prec: 80.00 € - il guadagno attuale è minore)
Mese 11: 50 € (media prec: 74.00 € - il guadagno attuale è minore)
Mese 12: 50 € (media prec: 71.82 € - il guadagno attuale è minore)
